### ISSUE TITLE
UI refinement to region selection

### ISSUE THREAD

**Issue by jywarren** [publiclab/colorimetry#15]
Follow-up to #3!

I noticed that if you just click instead of drag on this screen: 

![image](https://user-images.githubusercontent.com/24359/63363819-543c3300-c342-11e9-9635-12e74ff906bd.png)

It will still allow you to move forward. I think we need to:

1. set a minimum region size - maybe 10x10 pixels? 
2. display the selection even after you've finished selecting it - once you let go the mouse, it's not clear what you've selected
3. display both A and B selections on the final screen - it kind of seems confusing like the example red boxes were your selections, but that's not the case. Let's just show the actual selections you've made in the final screen, so you know exactly what's happend?

![image](https://user-images.githubusercontent.com/24359/63363961-9cf3ec00-c342-11e9-92b3-90f25e77d4d3.png)

This is going really well. Thanks, @Divy123 !

**Comment by Divy123** [comment]
Thanks @jywarren .

I will be incorporating them now.

**Comment by Divy123** [comment]
@jywarren working here:
https://divy123.github.io/colorimetry/public/

**Comment by jywarren** [comment]
Looking great! Can you add a color to the boxes you draw? Or make them red?
