### ISSUE TITLE
Colorimetry tool: Getting started

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [publiclab/colorimetry#2]
@jywarren 's approach to the problem:

> Process
> 
> So, I think we could basically approach this use case in 2 ways:
> 
> 1. We could have the starting module trigger 2 sequences, one for left and one for right. Each crops, then averages. Once both are done, we compare, for example, the average red channel of each.
> 
> 2. We run the left side (crop and average), then use the import-image module to re-import the original image, then run the right side. In the end, we look back and fetch the outputs from the two average steps (left and right), and compare the red channels of each.
>
> In both case we display the ratio of the red channel (for example) between the two sides.

Approach 1. is done in #1 to completion for the node context. Next steps: 
 - Integration of an image hosting service, we could host the generated outputs and return the image URL
 - For browser context, we need to create a canvas element and load those images into the sequencer. 
 - A boilerplate UI allowing us to load images and visualise the changes.

Some concerns to look into:

 - This will be built on the assumption that the input image(s) will be well lit and free of background noise (random backgrounds) and will only comprise of the test and the resulting image. This is because the crop module configs will have to be hardcoded differently for every input image, which is not possible. Perhaps a standard input format having half the test and half result image combined into one input image, which can then be safely cropped halfway and averaged, without worrying about `x, y` coordinates. This is one standardisation we'll have to make.

 - An accepted, standard measure for the colourimetry test. For now, it is to compare the channels of the images. In the future, something conforming to scientific standards will have to be developed.

@jywarren Also, it'd be great if you could publish the recent crop module bug fixes and support for new syntaxes to the NPM distribution, it'll be vital for this project.

**Comment by VibhorCodecianGupta** [comment]
#1 Approaches the problem in a node context, please have a look.

**Comment by jywarren** [comment]
For the time being, let's assume that people will not want to store the results online, as it could be sensitive health data. People can take a screenshot of their test, perhaps. This means it'll be good to include the image on the page, so you can see it, and the score, in the same screen on a smartphone. 

Let's also open a new issue for the "take a good image" UI. https://github.com/publiclab/colorimetry/issues/3

**Comment by Divy123** [comment]
I think we should proceed with 2nd approach as it stops the overkill of having to sequencer objets, can be more UI efficient.
Thoughts @jywarren @HarshKhandeparkar ?

**Comment by Divy123** [comment]
@jywarren request you to share your thoughts here, so that we can proceed further.

**Comment by jywarren** [comment]
Hi, all, I will do my best; we are in staff retreat this week so I'm a
little less available, apologies! Perhaps we should share some
sketches/diagrams of different ways we think this could work?

**Comment by Divy123** [comment]
Sure!!
Will do this as soon as possible.

**Comment by jywarren** [comment]
Hi all, i actually think either the parallel sequencers OR the single sequencer could work. I'm open to either. 

The key issue is when callbacks are run which will initiate the comparison and display a value. And on the input side, how smooth and intuitive the input image UI is; if we use a single sequencer, we should do our best to make sure it references the image from the earlier step (i believe it's possible to reference earlier step values, no?). 

In any case, the non-parallel case already works in `https://sequencer.publiclab.org/examples/#steps=crop{x:260|y:110|w:50|h:50},average{},import-image{},crop{x:500|y:110|w:50|h:50},average{}` but doesn't re-use the image from the first module. 

I think it's worth just making a PR with an `index.html` file that can have an image dropped into it just like on `image-sequencer` but only shows the numeric output. The simpler the better at this point in the process. Then we can start making improvements or modifications. Thanks!

**Comment by Divy123** [comment]
@jywarren request you to revert the merged PR here. I am working on the project here and going through the alternate path suggested by you.

**Comment by jywarren** [comment]
Can you incorporate the reverted work into your PR, or open a PR to revert?
Thanks!

**Comment by Divy123** [comment]
In the PR, I opened recently, I have already reverted this.
Thanks!

**Comment by jywarren** [comment]
This is going great. Closing now in favor of more specific issues, thanks!
